## Copyright 2020-2022 Josh Grancell. All rights reserved.
## Use of this source code is governed by an MIT License
## that can be found in the LICENSE file.
language: go

go:
  - 1.16.x
  - 1.17.x
  - tip

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
